### ISSUE TITLE
Create Database-Access-Class/Component

### ISSUE THREAD

**Issue by grittaweisheit** [MichaelBuessemeyer/MyTrainingsPal#19]
- [x]  create component that accesses the database
- [x] make it usable by other components and add it somewhere as an example or tell someone how to use it
- [x] implement some tests for the access (add, update, delete for all records we access during the app's operation)

**Comment by MichaelBuessemeyer** [comment]
I added tests for the daos. Testing the viewmodels seems to be quite difficult, as they somehow do not update the data they get form the db after an insert 🤷.

So I' assume testing the daos is enough.
